let a = 10
let b = 'test'
let soma

try {
    soma = a - c
} catch(error) {
    console.log('Algo deu errado ' + error)
}

// NOTE QUE MESMO TENDO ERRO NO CÓDIGO O try catch NÃO DEIXA O PROGRAMA PARAR
console.log('teste')